apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  replicas: 3 # 3 running copies
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: ryongg/sba_k8s:latest # Pull from my dockerhub image
        resources: # Set resources limit to ensure the app won't eat up CPU processing power
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
